version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    command: ["java", "App"]

volumes:
  mysql_data:
